name: Bump Patch Version
on:
  workflow_run:
    workflows: [Dependabot auto-merge]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git fetch origin main
          git pull origin main

      - name: Bump patch version
        run: |
          current_version=$(grep -m 1 "version" Cargo.toml | cut -d "\"" -f 2)
          new_version=$(echo $current_version | awk -F. '{$3 = $3 + 1; print}' OFS=".")
          awk -v current_version="$current_version" -v new_version="$new_version" '{gsub("version = \"" current_version "\"", "version = \"" new_version "\"")} 1' Cargo.toml > Cargo.toml.tmp && mv Cargo.toml.tmp Cargo.toml

          git add ./Cargo.toml

          tag_name="v$new_version"
          git tag $tag_name

          git push
          git push $tag_name

          echo "Bumped version from $current_version to $new_version"
