name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish:
    if: |
      github.event_name == 'pull_request' && github.event.pull_request.merged == true ||
      github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ryohidaka/action-cargo-publish@v0.1.0
        with:
          token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
